[package]
name = "vivox-rs"
version = "0.1.0"
authors = ["Joseph Zurowski <Dunklheit@users.noreply.github.com>"]
license = "Unlicense"
edition = "2018"

[lib]
name = "vivoxrs"
crate-type = ["cdylib"]

[build-dependencies]
bindgen = "0.54.1"

[dependencies]
