[package]
name = "vivox-rs"
version = "0.1.0"
authors = ["Joseph Zurowski <Dunklheit@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
